from __future__ import annotations

from pathlib import Path
from typing import Protocol

from csboard.domain.models import Project, Run


class ProjectRepository(Protocol):
    def create_project(self, project: Project) -> None: ...
    def get_project(self, project_id: str) -> Project: ...
    def save_project(self, project: Project) -> None: ...
    def create_run(self, run: Run) -> None: ...
    def get_run(self, project_id: str, run_id: str) -> Run: ...
    def save_run(self, run: Run) -> None: ...
    def project_dir(self, project_id: str) -> Path: ...


class ArtifactStore(Protocol):
    def commit_bytes(self, project_id: str, run_id: str, artifact_key: str, relative_path: str, payload: bytes, producer_stage: str) -> object: ...
    def invalidate_from(self, project_id: str, run_id: str, artifact_key: str, reason: str) -> list[str]: ...
