from __future__ import annotations

from pathlib import Path
from typing import Protocol

from csboard.domain.models import Task, Run


class TaskRepository(Protocol):
    def create_task(self, task: Task) -> None: ...
    def get_task(self, task_id: str) -> Task: ...
    def save_task(self, task: Task) -> None: ...
    def create_run(self, run: Run) -> None: ...
    def get_run(self, task_id: str, run_id: str) -> Run: ...
    def save_run(self, run: Run) -> None: ...
    def task_dir(self, task_id: str) -> Path: ...


class ArtifactStore(Protocol):
    def commit_bytes(self, task_id: str, run_id: str, artifact_key: str, relative_path: str, payload: bytes, producer_stage: str) -> object: ...
    def invalidate_from(self, task_id: str, run_id: str, artifact_key: str, reason: str) -> list[str]: ...
