import React, {useCallback, useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

async function request(path, options) {
  const response = await fetch(path, options);
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw Error(body.detail || body.message || '请求失败');
  return body;
}
const api = (path, options) => request(`/api/mountain${path}`, options);
const stages = [['segment-script', '文案智能分割'], ['clone-voice', '克隆参考音色'], ['storyboard', '拆分文案分镜'], ['illustrate', '生成统一插画'], ['whiteboard', '绘制白板动画'], ['compose', '合成音画成片']];

function navigate(path) { history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); }
function usePath() { const [path, setPath] = useState(location.pathname); useEffect(() => { const update = () => setPath(location.pathname); addEventListener('popstate', update); return () => removeEventListener('popstate', update); }, []); return path; }

function Navigation() { const path = usePath(); return <header className="topbar"><a className="brand" onClick={() => navigate('/create')}>CS Board <i>Mountain</i></a><nav>{[['/create', '新建制作'], ['/projects', '项目'], ['/settings', '设置'], ['/help', '帮助']].map(([href, label]) => <button key={href} className={path === href ? 'active' : ''} onClick={() => navigate(href)}>{label}</button>)}</nav></header>; }

function CreatePage() {
  const [title, setTitle] = useState(''); const [script, setScript] = useState(''); const [reference, setReference] = useState(); const [style, setStyle] = useState('极简粗线简笔白板风'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function save(start) { setBusy(true); setMessage(''); try {
    const created = await api('/projects', {method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify({title})});
    const form = new FormData(); form.append('script', script); form.append('reference', reference); form.append('style', style);
    await api(`/projects/${created.project_id}/inputs`, {method: 'POST', body: form});
    if (start) await api(`/projects/${created.project_id}/runs/${created.run_id}/start`, {method: 'POST'});
    navigate(`/projects/${created.project_id}`);
  } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  return <section><p className="eyebrow">标准白板制作 · mountain-av-v1</p><h1>从文案到可下载视频</h1><p className="lead">系统先确定文字、Voice Unit 与 Visual Item 的关系，再依真实语音时长完成同步。当前仅开放“白板动画 + 预设风格”。</p>
    <div className="form"><div className="grid"><Field label="项目名称"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="例如：市场风险提示" required /></Field><Field label="输出类型"><select disabled><option>白板动画（已开放）</option><option>动态信息图（暂未开放）</option></select></Field></div>
      <Field label="视频文案"><textarea value={script} onChange={e => setScript(e.target.value)} placeholder="输入完整口播文案……" minLength="10" required /></Field>
      <div className="grid"><Field label="参考音频"><input type="file" accept="audio/*" onChange={e => setReference(e.target.files[0])} required /><small>WAV、MP3、M4A、OGG 或 FLAC；推荐 10–30 秒清晰单人说话。</small></Field><Field label="预设白板风格"><select value={style} onChange={e => setStyle(e.target.value)}><option>极简粗线简笔白板风</option><option>纸艺隐喻白板风</option></select></Field></div>
      <p className="hint">“保存项目”不会启动模型，可稍后在工作台开始；“保存并开始”会直接进入自动六阶段流程。</p>{message && <p className="error">{message}</p>}<p><button disabled={busy || !title || script.length < 10 || !reference} onClick={() => save(false)}>保存项目</button> <button className="primary" disabled={busy || !title || script.length < 10 || !reference} onClick={() => save(true)}>{busy ? '正在提交…' : '保存并开始制作'}</button></p>
    </div></section>;
}
function Field({label, children}) { return <label className="field"><span>{label}</span>{children}</label>; }

function WorkbenchPage({projectId}) {
  const [view, setView] = useState(); const [units, setUnits] = useState([]); const [events, setEvents] = useState([]); const [message, setMessage] = useState('');
  const refresh = useCallback(async () => { try { const detail = await api(`/projects/${projectId}`); setView(detail); const runId = detail.active_run?.run_id; if (runId) { const [unitView, eventView] = await Promise.all([api(`/projects/${projectId}/runs/${runId}/units`), api(`/projects/${projectId}/runs/${runId}/events`)]); setUnits(unitView.items); setEvents(eventView.items); } } catch (error) { setMessage(error.message); } }, [projectId]);
  useEffect(() => { refresh(); const timer = setInterval(refresh, 2500); return () => clearInterval(timer); }, [refresh]);
  const run = view?.active_run; const runId = run?.run_id; const stateByName = Object.fromEntries((view?.stages || []).map(item => [item.stage, item]));
  async function command(name) { try { if (name === 'start') await api(`/projects/${projectId}/runs/${runId}/start`, {method: 'POST'}); else if (name === 'diagnostics') { const result = await api(`/projects/${projectId}/runs/${runId}/diagnostics`, {method: 'POST'}); open(result.download_url, '_blank'); } else await api(`/projects/${projectId}/runs/${runId}/${name}`, {method: 'POST'}); setMessage('命令已提交。'); refresh(); } catch (error) { setMessage(error.message); } }
  if (!view) return <section>正在载入项目…</section>;
  const final = `/api/mountain/projects/${projectId}/runs/${runId}/final`;
  return <><button className="back" onClick={() => navigate('/projects')}>← 返回项目</button><section><div className="workhead"><div><p className="eyebrow">制作工作台</p><h1>{view.project.title}</h1><small>Run：{runId} · Trace：{view.trace?.trace_id}</small></div><b className={`badge ${run.status}`}>{run.status}</b></div><div className="commands">{run.status === 'pending' && <button className="primary" onClick={() => command('start')}>开始制作</button>}{run.status === 'running' && <button onClick={() => command('cancel')}>取消运行</button>}{run.status === 'failed' && <button className="primary" onClick={() => command('retry')}>重试运行</button>}<button onClick={() => command('diagnostics')}>导出诊断包</button></div>{message && <p className="notice">{message}</p>}
    <div className="stage-grid">{stages.map(([id, label], index) => { const state = stateByName[id] || {status: 'pending'}; return <article key={id} className={`stage ${state.status}`}><b>{String(index + 1).padStart(2, '0')}</b><div><h3>{label}</h3><small>{state.status} · 第 {state.attempt || 0} 次</small></div></article>; })}</div>
    {run.status === 'failed' && <div className="failure"><b>制作失败</b><p>{view.warnings?.at(-1)?.message || '请导出诊断包分析。'}</p></div>}
    {run.status === 'succeeded' && <div className="result"><h2>成片已生成</h2><video controls src={final} /><p><a className="primary" href={final}>下载 MP4 成片</a></p></div>}
  </section><section className="workgrid"><article><h2>Voice Unit / Visual Item</h2>{units.length ? units.map(unit => <div className="unit" key={unit.unit_id}><b>{unit.order}. {unit.text}</b><small>{unit.timing?.alignment_source || '语音尚未生成'} · {unit.timing?.duration_ms ? `${unit.timing.duration_ms}ms` : ''}</small>{unit.visual_items?.map(visual => <span key={visual.visual_id}>{visual.visual_id}：{visual.text}</span>)}</div>) : <p>文案分割完成后显示 Unit、文字范围、时长与同步 fallback。</p>}</article><article><h2>产物</h2>{view.artifacts.length ? view.artifacts.map(item => <p key={item.artifact_key}><a href={`/api/mountain/projects/${projectId}/runs/${runId}/artifacts/${item.artifact_key}`}>{item.artifact_key}</a><small>{item.status} · {item.sha256?.slice(0, 12)}</small></p>) : <p>尚无可下载产物。</p>}<h2>活动</h2>{events.slice(-8).reverse().map(event => <p key={event.sequence}><small>#{event.sequence} {event.event_type || event.action || '运行事件'}</small></p>)}</article></section></>;
}

function ProjectsPage() { const [items, setItems] = useState([]); const [error, setError] = useState(''); useEffect(() => { api('/projects').then(value => setItems(value.items)).catch(e => setError(e.message)); }, []); return <section><p className="eyebrow">项目库</p><h1>所有制作项目</h1>{error && <p className="error">{error}</p>}<div className="projects">{items.length ? items.map(item => <article key={item.project_id}><div><b>{item.title}</b><small>{item.project_id} · {item.status}</small></div><button onClick={() => navigate(`/projects/${item.project_id}`)}>打开工作台</button></article>) : <p>还没有项目。</p>}</div></section>; }
function SettingsPage() { const [config, setConfig] = useState(); const [message, setMessage] = useState(''); useEffect(() => { request('/api/config').then(setConfig).catch(e => setMessage(e.message)); }, []); if (!config) return <section>正在读取设置…</section>; const set = (key, value) => setConfig({...config, [key]: value}); const textPath = config.llm_api_mode === 'responses' ? '/responses' : '/chat/completions'; async function save(test) { try { const result = await request(test ? '/api/config/test' : '/api/config', {method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify(config)}); setMessage(test ? Object.values(result).map(value => value.message).join('；') : '设置已保存。'); } catch (error) { setMessage(error.message); } } return <section><p className="eyebrow">服务设置与接口</p><h1>LLM API Key 与本地能力</h1><p className="lead">Key 只保存于本机后端，页面仅显示掩码或已配置状态。</p><div className="endpoints"><p><b>文案分镜</b><code>{config.base_url?.replace(/\/$/, '')}{textPath}</code></p><p><b>统一插画</b><code>{config.base_url?.replace(/\/$/, '')}/images/generations</code></p><p><b>音色克隆</b><code>{config.tts_url?.replace(/\/$/, '')}/gradio_api/call/gen_single</code></p></div><Field label="OpenAI 兼容 API Key"><input type="password" value={config.api_key || ''} placeholder={config.has_api_key ? '已配置（已脱敏）' : '未配置'} onChange={e => set('api_key', e.target.value)} /></Field><div className="grid"><Field label="API Base URL"><input value={config.base_url || ''} onChange={e => set('base_url', e.target.value)} /></Field><Field label="文本协议"><select value={config.llm_api_mode || 'chat-completions'} onChange={e => set('llm_api_mode', e.target.value)}><option value="chat-completions">chat-completions</option><option value="responses">responses</option></select></Field><Field label="文案模型"><input value={config.text_model || ''} onChange={e => set('text_model', e.target.value)} /></Field><Field label="插画模型"><input value={config.image_model || ''} onChange={e => set('image_model', e.target.value)} /></Field><Field label="IndexTTS 地址"><input value={config.tts_url || ''} onChange={e => set('tts_url', e.target.value)} /></Field></div><p><button className="primary" onClick={() => save(false)}>保存设置</button> <button onClick={() => save(true)}>测试接口</button></p>{message && <p className="notice">{message}</p>}</section>; }
function HelpPage() { return <section><p className="eyebrow">帮助</p><h1>标准制作流程</h1><ol><li>在设置页配置并测试 LLM API Key 和 IndexTTS。</li><li>保存文案、参考音频与风格；可先保存，稍后启动。</li><li>工作台跟踪六阶段，出现错误时查看 Trace、活动和诊断包。</li><li>成片通过 A/V 校验后可预览并下载 MP4。</li></ol></section>; }
function App() { const path = usePath(); const match = path.match(/^\/projects\/([^/]+)$/); return <main><Navigation />{path === '/projects' ? <ProjectsPage /> : match ? <WorkbenchPage projectId={match[1]} /> : path === '/settings' ? <SettingsPage /> : path === '/help' ? <HelpPage /> : <CreatePage />}</main>; }
createRoot(document.getElementById('root')).render(<App />);
