import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, fireEvent, waitFor, act } from '@testing-library/react'
import { MemoryRouter, Routes, Route } from 'react-router-dom'
import { CreateTaskPage } from '../src/pages/CreateTaskPage'

const createOk = { ok: true, command: 'task.create', task_id: 't/special', run_id: 'r1', trace_id: 'tr', command_id: 'c', event_sequence: 1 }
const saveOk = { ok: true, task_id: 't/special', input_saved: true }
const styles = { items: [{ style_id: 's1', kind: 'preset', name: '水彩白板', description: '', engine: 'whiteboard', status: 'active', revision: 1, tags: [], prompt_text: null, negative_prompt: null, preview_asset_id: null, created_at: '', updated_at: '' }], next_cursor: null, total: 1 }
const voices = { items: [{ voice_id: 'v1', name: '女声示例', tags: [], duration_ms: 1000, sample_rate: 24000, channels: 1, format: 'wav', enabled: true, status: 'active', created_at: '', updated_at: '' }], next_cursor: null, total: 1 }
const json = (body: unknown, status = 200) => ({ ok: status >= 200 && status < 300, status, headers: new Headers({ 'content-type': 'application/json' }), json: () => Promise.resolve(body) })
const fetchMock = vi.fn()
beforeEach(() => { fetchMock.mockReset(); fetchMock.mockImplementation((url: string) => { const u = String(url); if (u.includes('/assets/styles')) return json(styles); if (u.includes('/assets/voices')) return json(voices); if (u.endsWith('/inputs')) return json(saveOk); if (u.endsWith('/tasks')) return json(createOk); return json({}, 404) }); vi.stubGlobal('fetch', fetchMock) })
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks() })
function renderPage() { return render(<MemoryRouter initialEntries={['/tasks/new']} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /><Route path="/tasks/:id" element={<div>task-detail</div>} /><Route path="/" element={<div>task-list</div>} /></Routes></MemoryRouter>) }
async function ready() { renderPage(); await waitFor(() => expect(fetchMock.mock.calls.filter(c => String(c[0]).includes('/assets/')).length).toBe(2)) }
const clickTab = (name: string) => fireEvent.click(screen.getByRole('tab', { name: new RegExp(name) }))
function fillTitle() { fireEvent.change(screen.getByLabelText('任务名称'), { target: { value: '量子计算科普' } }) }
function fillScript() { clickTab('视频文案'); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '这是一段不少于十个字的测试文案。' } }); fireEvent.click(screen.getByRole('button', { name: '下一步' })) }
function fillReference() { clickTab('声音生成'); fireEvent.change(screen.getByLabelText('参考音频文件'), { target: { files: [new File(['audio'], 'ref.wav', { type: 'audio/wav' })] } }); fireEvent.click(screen.getByRole('button', { name: '下一步' })) }
function reachFinal() { fillTitle(); fillScript(); fillReference(); fireEvent.click(screen.getByRole('button', { name: '下一步' })); fireEvent.click(screen.getByRole('button', { name: '下一步' })) }

describe('六 Tab user flow', () => {
  it('renders six tabs and preserves input while navigating', async () => { await ready(); expect(screen.getAllByRole('tab')).toHaveLength(6); fillTitle(); clickTab('视频文案'); expect(screen.getByLabelText('原始文案')).toBeInTheDocument(); clickTab('任务介绍'); expect(screen.getByLabelText('任务名称')).toHaveValue('量子计算科普') })
  it('validates script length and char rules', async () => { await ready(); fillTitle(); clickTab('视频文案'); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '太短' } }); fireEvent.click(screen.getByRole('button', { name: '下一步' })); expect(screen.getByText('文案不少于 10 字')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '这是一段不少于十个字的测试文案。' } }); fireEvent.change(screen.getByLabelText('目标'), { target: { value: '1.5' } }); fireEvent.click(screen.getByRole('button', { name: '下一步' })); expect(screen.getByText('字数必须为整数')).toBeInTheDocument() })
  it('requires reference and accepts legal audio FormData', async () => { await ready(); fillTitle(); fillScript(); fireEvent.click(screen.getByRole('button', { name: '下一步' })); expect(screen.getByText('首次保存必须上传参考音频文件')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('参考音频文件'), { target: { files: [new File(['audio'], 'ref.wav', { type: 'audio/wav' })] } }); expect(screen.getByLabelText('参考音频文件')).toBeInTheDocument() })
  it('shows real styles and voices success/empty/error states', async () => { await ready(); clickTab('声音生成'); expect(screen.getByText('女声示例')).toBeInTheDocument(); clickTab('视觉设置'); await waitFor(() => expect(screen.getByText('水彩白板')).toBeInTheDocument()) })
  it('submits style name and no unsupported fields', async () => { await ready(); reachFinal(); clickTab('视觉设置'); fireEvent.click(screen.getByRole('button', { name: /水彩白板/ })); clickTab('成片设置'); fireEvent.click(screen.getByRole('button', { name: '创建并保存' })); await waitFor(() => expect(screen.getByText('task-detail')).toBeInTheDocument()); const form = fetchMock.mock.calls.find(c => String(c[0]).endsWith('/inputs'))[1].body as FormData; expect(form.get('style')).toBe('水彩白板'); expect(form.get('voice_id')).toBeNull(); expect(form.get('style_id')).toBeNull(); expect(form.get('execution_strategy')).toBeNull(); expect(form.get('shots_per_image')).toBeNull() })
  it('disables dynamic infographic', async () => { await ready(); clickTab('输出类型'); expect(screen.getByText('动态信息图').closest('.choice-card')).toHaveClass('disabled') })
  it('creates once and retries same task after upload failure', async () => { let uploads = 0; fetchMock.mockImplementation((url: string) => { const u = String(url); if (u.includes('/assets/styles')) return json(styles); if (u.includes('/assets/voices')) return json(voices); if (u.endsWith('/inputs')) return ++uploads === 1 ? json({ detail: { code: 'UPLOAD_FAILED', message: '保存输入失败' } }, 400) : json(saveOk); return json(createOk) }); await ready(); reachFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存' })); await waitFor(() => expect(screen.getByText('任务已创建、输入保存失败')).toBeInTheDocument()); expect(fetchMock.mock.calls.filter(c => String(c[0]).endsWith('/tasks'))).toHaveLength(1); fireEvent.click(screen.getByRole('button', { name: '重试保存' })); await waitFor(() => expect(screen.getByText('task-detail')).toBeInTheDocument()); expect(fetchMock.mock.calls.filter(c => String(c[0]).endsWith('/tasks'))).toHaveLength(1); expect(uploads).toBe(2) })
  it('double submit is idempotent', async () => { await ready(); reachFinal(); const form = screen.getByRole('button', { name: '创建并保存' }).closest('form')!; fireEvent.submit(form); fireEvent.submit(form); await waitFor(() => expect(fetchMock.mock.calls.filter(c => String(c[0]).endsWith('/tasks'))).toHaveLength(1)) })
  it('asset rejection after unmount has no warnings', async () => { let rejectStyles!: (e: Error) => void; let rejectVoices!: (e: Error) => void; fetchMock.mockImplementation((url: string) => String(url).includes('/assets/styles') ? new Promise((_, r) => { rejectStyles = r }) : String(url).includes('/assets/voices') ? new Promise((_, r) => { rejectVoices = r }) : json({}, 404)); const error = vi.spyOn(console, 'error'); const warn = vi.spyOn(console, 'warn'); const { unmount } = renderPage(); unmount(); await act(async () => { rejectStyles(new Error('offline')); rejectVoices(new Error('offline')) }); expect(error).not.toHaveBeenCalled(); expect(warn).not.toHaveBeenCalled() })
  it('renders safe error only', async () => { fetchMock.mockImplementation((url: string) => { const u = String(url); if (u.includes('/assets/styles')) return json(styles); if (u.includes('/assets/voices')) return json(voices); if (u.endsWith('/tasks')) return json(createOk); return json({ detail: { code: 'SENSITIVE', message: '安全错误信息', details: { path: '/secret', token: 'sk-live' } } }, 400) }); await ready(); reachFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存' })); await waitFor(() => expect(screen.getByText('安全错误信息')).toBeInTheDocument()); expect(screen.queryByText('/secret')).toBeNull(); expect(screen.queryByText('sk-live')).toBeNull() })
})
