/** CCF-TASK-CREATE-SIX-TAB-18 — explicit test fixtures for the real API boundary. */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, fireEvent, waitFor, act, cleanup } from '@testing-library/react'
import { StrictMode } from 'react'
import { MemoryRouter, Routes, Route } from 'react-router-dom'
import { CreateTaskPage, splitScriptIntoSegments } from '../src/pages/CreateTaskPage'

const OPTIONS = {
  engines: [{ id: 'whiteboard', label: '白板动画', available: true }, { id: 'infographic', label: '动态信息图', available: false, reason: 'CAPABILITY_NOT_AVAILABLE' }],
  visual_sources: [{ id: 'preset', label: '预设风格', available: true }, { id: 'custom-reference', label: '自定义参考', available: false, reason: 'CAPABILITY_NOT_AVAILABLE' }],
  voice_sources: [{ id: 'voice-asset', label: '真实音色资产', available: true }, { id: 'uploaded-reference', label: '上传参考音频', available: true }],
  limits: { script_min_chars: 10, target_chars_min: 5, target_chars_max: 500, brand_text_max_chars: 12 },
  defaults: { engine: 'whiteboard', visual_source: 'preset', target_chars: 45, shots_per_image: 2, line_density: 'rich', visual_anchor_enabled: true, include_subtitles: true },
}
const VOICES = { items: [{ voice_id: 'voice-real', name: '真实女声', description: '测试音色', tags: ['中文'], duration_ms: 3200, sample_rate: 48000, channels: 1, format: 'wav', enabled: true, status: 'active', content_url: null, created_at: '', updated_at: '' }, { voice_id: 'voice-disabled', name: '已停用音色', description: '', tags: [], duration_ms: 1000, sample_rate: 48000, channels: 1, format: 'wav', enabled: false, status: 'inactive', content_url: null, created_at: '', updated_at: '' }], next_cursor: null, total: 2 }
const STYLES = { items: [{ style_id: 'style-real', kind: 'preset', name: '真实水彩', description: '测试风格', engine: 'whiteboard', status: 'active', revision: 1, tags: ['水彩'], prompt_text: null, negative_prompt: null, preview_asset_id: 'preview-1', config: {}, created_at: '', updated_at: '' }, { style_id: 'style-disabled', kind: 'preset', name: '停用风格', description: '', engine: 'whiteboard', status: 'inactive', revision: 1, tags: [], prompt_text: null, negative_prompt: null, preview_asset_id: null, config: {}, created_at: '', updated_at: '' }], next_cursor: null, total: 2 }
const CREATED = { ok: true, command: 'task.create', task_id: 'task-new', run_id: 'run-new', trace_id: 'trace-new', command_id: 'cmd-new', event_sequence: 1 }
const SAVED = { ok: true, task_id: 'task-new', input_saved: true, execution_plan: { mode: 'legacy' } }
const RECOVERY_TASK = { task: { task_id: 'task-recovered', title: '恢复任务', summary: '恢复摘要', engine: 'whiteboard', active_run_id: 'run-recovered' }, active_run: { task_id: 'task-recovered', run_id: 'run-recovered' }, stages: [], warnings: [], artifacts: [], trace: { trace_id: 'trace-recovered', command_ids: [] } }
function recoveryInputs(uploaded = true) { return { task_id: 'task-recovered', saved: true, inputs: { script: '恢复文案内容足够长。', style: 'style-real', voice_source: 'voice-asset', voice_asset_id: 'voice-real', visual_source: 'preset', style_asset_id: 'style-real', target_chars: 20, shots_per_image: 3, line_density: 'minimal', brand_text: '恢复品牌', include_subtitles: false, pen_text: '', stroke_detail: '' }, reference_audio: { uploaded, filename: uploaded ? 'old.wav' : null }, rules: { target_chars: 20, min_chars: 1, max_chars: 500 }, script_preparation: null, visual_anchor_enabled: false, execution_plan: { mode: 'legacy' } } }
const fetchMock = vi.fn()

function json(body: unknown, status = 200) { return { ok: status >= 200 && status < 300, status, json: () => Promise.resolve(body), headers: new Headers({ 'content-type': 'application/json' }) } }
function defaultFetch(url: string) {
  const value = String(url)
  if (value.endsWith('/tasks/create-options')) return json(OPTIONS)
  if (value.includes('/assets/voices')) return json(VOICES)
  if (value.includes('/assets/styles')) return json(STYLES)
  if (value.endsWith('/inputs')) return json(SAVED)
  if (value.endsWith('/tasks')) return json(CREATED)
  return json({ error: { code: 'NOT_FOUND', message: '未找到' } }, 404)
}
beforeEach(() => { fetchMock.mockReset(); fetchMock.mockImplementation(defaultFetch); vi.stubGlobal('fetch', fetchMock) })
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks() })
function renderPage() { return render(<MemoryRouter initialEntries={['/tasks/new']} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /><Route path="/tasks/:id" element={<div data-testid="active-workbench">任务工作台</div>} /><Route path="/" element={<div>任务队列</div>} /></Routes></MemoryRouter>) }
function next() { fireEvent.click(screen.getByRole('button', { name: '下一步' })) }
function goFinal() { for (let i = 0; i < 4; i += 1) next() }
function createCalls() { return fetchMock.mock.calls.filter((call) => String(call[0]).endsWith('/tasks')) }
function inputCalls() { return fetchMock.mock.calls.filter((call) => String(call[0]).endsWith('/inputs')) }
function inputSaveCalls() { return fetchMock.mock.calls.filter((call) => String(call[0]).endsWith('/inputs') && call[1]?.method === 'POST') }
async function ready() { await waitFor(() => expect(screen.getByRole('tab', { name: '任务介绍' })).toBeInTheDocument()) }
function fillIntroAndScript() { fireEvent.change(screen.getByLabelText('任务名称'), { target: { value: '测试任务' } }); fireEvent.change(screen.getByLabelText('任务摘要'), { target: { value: '用于自动化验收的摘要' } }); next(); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '第一句完整内容。第二句完整内容！第三句完整内容？' } }) }
function renderRecoveryRoute(taskId = 'task-recovered', runId = 'run-recovered') { return render(<MemoryRouter initialEntries={[`/tasks/new?task_id=${taskId}&run_id=${runId}&tab=final`]} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /><Route path="/tasks/:id" element={<div data-testid="active-workbench">任务工作台</div>} /></Routes></MemoryRouter>) }
function recoveryPage(taskId = 'task-recovered', runId = 'run-recovered', inputBody = recoveryInputs()) { fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith(`/tasks/${taskId}/inputs`)) return json({ ...inputBody, task_id: taskId }); if (value.endsWith(`/tasks/${taskId}`)) return json({ ...RECOVERY_TASK, task: { ...RECOVERY_TASK.task, task_id: taskId, active_run_id: runId }, active_run: { ...RECOVERY_TASK.active_run, task_id: taskId, run_id: runId } }); return defaultFetch(url) }); return renderRecoveryRoute(taskId, runId) }

describe('CreateTaskPage six-tab preview-first flow', () => {
  it('shows tabs in the contract order and preserves fields across navigation', async () => {
    renderPage(); await ready()
    expect(screen.getAllByRole('tab').map((tab) => tab.textContent?.trim())).toEqual(['任务介绍', '视频文案0', '声音生成', '输出类型', '视觉设置', '成片设置'])
    fireEvent.change(screen.getByLabelText('任务名称'), { target: { value: '跨 Tab 状态' } }); next(); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '保留这段跨 Tab 的测试文案。' } }); fireEvent.click(screen.getByRole('tab', { name: '任务介绍' })); expect(screen.getByLabelText('任务名称')).toHaveValue('跨 Tab 状态'); next(); expect(screen.getByLabelText('原始文案')).toHaveValue('保留这段跨 Tab 的测试文案。')
  })
  it('moves roving focus and exposes a matching active tabpanel for keyboard navigation', async () => {
    renderPage(); await ready(); const intro = screen.getByRole('tab', { name: '任务介绍' }); fireEvent.keyDown(intro, { key: 'ArrowRight' }); const script = screen.getByRole('tab', { name: /视频文案/ }); expect(script).toHaveFocus(); expect(script).toHaveAttribute('tabindex', '0'); expect(intro).toHaveAttribute('tabindex', '-1'); expect(screen.getByRole('tabpanel')).toHaveAttribute('id', 'tab-panel-script'); expect(script).toHaveAttribute('aria-controls', 'tab-panel-script'); fireEvent.keyDown(script, { key: 'ArrowLeft' }); expect(intro).toHaveFocus(); fireEvent.keyDown(intro, { key: 'End' }); const final = screen.getByRole('tab', { name: '成片设置' }); expect(final).toHaveFocus(); fireEvent.keyDown(final, { key: 'Home' }); expect(intro).toHaveFocus(); expect(screen.getByRole('tabpanel')).toHaveAttribute('aria-labelledby', 'tab-intro')
  })
  it('renders complete-sentence preview and live character count', async () => {
    renderPage(); await ready(); next(); const script = screen.getByLabelText('原始文案'); fireEvent.change(script, { target: { value: '甲句。乙句！丙句？' } }); fireEvent.change(screen.getByLabelText('目标分段长度'), { target: { value: '3' } }); expect((document.querySelector('textarea.preview') as HTMLTextAreaElement).value).toBe('甲句。\n\n乙句！\n\n丙句？'); expect(screen.getByText('实时字数：').parentElement).toHaveTextContent('9'); expect(screen.getByText(/提交前预览/)).toBeInTheDocument()
  })
  it('loads real voice/style assets with preview URLs and visible disabled state', async () => {
    renderPage(); await ready(); fireEvent.click(screen.getByRole('tab', { name: '声音生成' })); await waitFor(() => expect(screen.getAllByText('真实女声').length).toBeGreaterThan(0)); expect(screen.getByText('已停用音色（不可用）')).toBeInTheDocument(); expect(document.querySelectorAll('audio')).toHaveLength(1); expect(document.querySelector('audio')).toHaveAttribute('src', expect.stringContaining('/assets/voices/voice-real/content')); fireEvent.click(screen.getByRole('tab', { name: '视觉设置' })); await waitFor(() => expect(screen.getByText('真实水彩')).toBeInTheDocument()); expect(screen.getByText('停用风格（不可用）')).toBeInTheDocument(); expect(screen.getByAltText('真实水彩 预览')).toHaveAttribute('src', expect.stringContaining('/assets/blobs/preview-1')); expect(fetchMock.mock.calls.some((call) => String(call[0]).includes('/assets/styles?kind=preset&engine=whiteboard'))).toBe(true)
  })
  it('keeps unavailable engine/source visible and disabled with server reason', async () => {
    renderPage(); await ready(); fireEvent.click(screen.getByRole('tab', { name: '输出类型' })); expect(screen.getByRole('button', { name: /动态信息图/ })).toBeDisabled(); expect(screen.getByText(/CAPABILITY_NOT_AVAILABLE/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('tab', { name: '视觉设置' })); expect(screen.getByRole('button', { name: /自定义参考/ })).toBeDisabled()
  })
  it('shows a real options error and keeps preview navigation available', async () => {
    fetchMock.mockImplementation((url) => String(url).endsWith('/tasks/create-options') ? json({ error: { code: 'OPTIONS_UNAVAILABLE', message: '选项接口待联调' } }, 503) : defaultFetch(url))
    renderPage(); await waitFor(() => expect(screen.getByText(/选项接口待联调/)).toBeInTheDocument()); next(); expect(screen.getByLabelText('原始文案')).toBeInTheDocument(); goFinal(); expect(screen.getByRole('button', { name: '创建并保存 Task' })).toBeDisabled()
  })
  it('starts with the shared 45/2/rich defaults before any recovery', async () => {
    renderPage(); await ready(); fireEvent.click(screen.getByRole('tab', { name: /视频文案/ })); expect(screen.getByLabelText('目标分段长度')).toHaveValue(45); fireEvent.click(screen.getByRole('tab', { name: /成片设置/ })); expect(screen.getByLabelText('每张图分镜数')).toHaveValue('2'); expect(screen.getByLabelText('线条绘制量')).toHaveValue('rich')
  })
  it('keeps recovered values when options resolve before or after recovery', async () => {
    let resolveOptions!: (value: unknown) => void; fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-recovered')) return json(RECOVERY_TASK); if (value.endsWith('/tasks/task-recovered/inputs')) return json(recoveryInputs()); if (value.endsWith('/tasks/create-options')) return new Promise((resolve) => { resolveOptions = resolve }); return defaultFetch(url) }); const view = render(<MemoryRouter initialEntries={['/tasks/new?task_id=task-recovered&run_id=run-recovered&tab=final']} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /></Routes></MemoryRouter>); await waitFor(() => expect(screen.getByLabelText('每张图分镜数')).toHaveValue('3')); fireEvent.click(screen.getByRole('tab', { name: /视频文案/ })); await waitFor(() => expect(screen.getByLabelText('目标分段长度')).toHaveValue(20)); await act(async () => resolveOptions(json(OPTIONS))); expect(screen.getByLabelText('目标分段长度')).toHaveValue(20); view.unmount()
    let resolveInputsSecond!: (value: unknown) => void; fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-recovered')) return json(RECOVERY_TASK); if (value.endsWith('/tasks/task-recovered/inputs')) return new Promise((resolve) => { resolveInputsSecond = resolve }); if (value.endsWith('/tasks/create-options')) return json(OPTIONS); return defaultFetch(url) }); render(<MemoryRouter initialEntries={['/tasks/new?task_id=task-recovered&run_id=run-recovered&tab=final']} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /></Routes></MemoryRouter>); await act(async () => resolveInputsSecond(json(recoveryInputs()))); await waitFor(() => expect(screen.getByLabelText('线条绘制量')).toHaveValue('minimal')); fireEvent.click(screen.getByRole('tab', { name: /视频文案/ })); expect(screen.getByLabelText('目标分段长度')).toHaveValue(20)
  })
  it('renders the final summary from all six-tab selections', async () => {
    renderPage(); await ready(); fillIntroAndScript(); next(); await waitFor(() => expect(screen.getAllByText('真实女声').length).toBeGreaterThan(0)); next(); next(); fireEvent.click(screen.getByRole('tab', { name: '视觉设置' })); await waitFor(() => expect(screen.getByText('真实水彩')).toBeInTheDocument()); next(); expect(screen.getByText('最终汇总')).toBeInTheDocument(); expect(screen.getByText(/测试任务/)).toBeInTheDocument(); expect(screen.getByText(/真实水彩/)).toBeInTheDocument()
  })
})

describe('CreateTaskPage real submission contract', () => {
  it('sends one create JSON then one multipart input payload and never starts a run', async () => {
    renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByText('任务工作台')).toBeInTheDocument()); expect(createCalls()).toHaveLength(1); expect(inputCalls()).toHaveLength(1)
    const createOptions = createCalls()[0][1]; expect(JSON.parse(createOptions.body)).toMatchObject({ title: '测试任务', summary: '用于自动化验收的摘要', engine: 'whiteboard', pipeline_id: 'mountain-av-v1' }); const submissionId = JSON.parse(createOptions.body).submission_id as string; expect(submissionId).toEqual(expect.any(String)); expect(submissionId.length).toBeGreaterThanOrEqual(16); expect(new Set(submissionId).size / submissionId.length).toBeGreaterThanOrEqual(0.45); const inputOptions = inputCalls()[0][1]; expect(inputOptions.method).toBe('POST'); expect(inputOptions.body).toBeInstanceOf(FormData); const body = inputOptions.body as FormData; expect(body.get('script')).toContain('第一句'); expect(body.get('target_chars')).toBe('45'); expect(body.get('voice_source')).toBe('voice-asset'); expect(body.get('voice_asset_id')).toBe('voice-real'); expect(body.get('visual_source')).toBe('preset'); expect(body.get('style_asset_id')).toBe('style-real'); expect(body.get('shots_per_image')).toBe('2'); expect(body.get('line_density')).toBe('rich'); expect(body.get('visual_anchor_enabled')).toBe('true'); expect(body.get('include_subtitles')).toBe('true'); expect(fetchMock.mock.calls.some((call) => /\/start|\/stages\/|\/gate/i.test(String(call[0])))).toBe(false)
  })
  it('double submit creates only one Task', async () => {
    let resolveCreate!: (value: unknown) => void; fetchMock.mockImplementation((url) => String(url).endsWith('/tasks') ? new Promise((resolve) => { resolveCreate = resolve }) : defaultFetch(url)); renderPage(); await ready(); fillIntroAndScript(); goFinal(); const form = screen.getByRole('button', { name: '创建并保存 Task' }).closest('form')!; fireEvent.submit(form); fireEvent.submit(form); expect(createCalls()).toHaveLength(1); await act(async () => resolveCreate(json(CREATED))); await waitFor(() => expect(inputCalls()).toHaveLength(1)); expect(createCalls()).toHaveLength(1)
  })
  it('reuses the submission id after a response-lost create retry', async () => {
    let attempts = 0; fetchMock.mockImplementation((url) => { if (String(url).endsWith('/tasks')) { attempts += 1; return attempts === 1 ? Promise.reject(new Error('network socket /mnt/private/token=secret')) : json(CREATED) }; return defaultFetch(url) }); renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByText(/网络请求失败，请稍后重试/)).toBeInTheDocument()); const firstBody = JSON.parse(createCalls()[0][1].body); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByTestId('active-workbench')).toBeInTheDocument()); const secondBody = JSON.parse(createCalls()[1][1].body); expect(secondBody.submission_id).toBe(firstBody.submission_id); expect(inputCalls()).toHaveLength(1)
  })
  it('creates only once under StrictMode and keeps create/save loading states disabled', async () => {
    let resolveCreate!: (value: unknown) => void; let resolveSave!: (value: unknown) => void; fetchMock.mockImplementation((url, init) => { const value = String(url); if (value.endsWith('/tasks')) return new Promise((resolve) => { resolveCreate = resolve }); if (value.endsWith('/inputs') && init?.method === 'POST') return new Promise((resolve) => { resolveSave = resolve }); return defaultFetch(url) }); render(<StrictMode><MemoryRouter initialEntries={['/tasks/new']} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /><Route path="/tasks/:id" element={<div>任务工作台</div>} /></Routes></MemoryRouter></StrictMode>); await ready(); fillIntroAndScript(); goFinal(); const button = screen.getByRole('button', { name: '创建并保存 Task' }); await waitFor(() => expect(button).toBeEnabled()); fireEvent.click(button); expect(button).toBeDisabled(); expect(createCalls()).toHaveLength(1); await act(async () => resolveCreate(json(CREATED))); await waitFor(() => expect(inputSaveCalls()).toHaveLength(1)); expect(screen.getByRole('button', { name: '重试保存输入' })).toBeDisabled(); await act(async () => resolveSave(json(SAVED))); await waitFor(() => expect(screen.getByText('任务工作台')).toBeInTheDocument())
  })
  it('create failure keeps all entered fields and sends no input request', async () => {
    fetchMock.mockImplementation((url) => String(url).endsWith('/tasks') ? json({ error: { code: 'CREATE_FAILED', message: '创建失败（测试）' } }, 400) : defaultFetch(url)); renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByText(/创建失败（测试）/)).toBeInTheDocument()); expect(inputCalls()).toHaveLength(0); fireEvent.click(screen.getByRole('tab', { name: '任务介绍' })); expect(screen.getByLabelText('任务名称')).toHaveValue('测试任务')
  })
  it('input failure exposes task/run and retry only calls input save', async () => {
    let attempts = 0; fetchMock.mockImplementation((url) => { if (String(url).endsWith('/inputs')) { attempts += 1; return attempts === 1 ? json({ error: { code: 'INPUT_FAILED', message: '输入保存失败（测试）' } }, 400) : json(SAVED) }; return defaultFetch(url) }); renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByText(/输入保存失败（测试）/)).toBeInTheDocument()); expect(screen.getByText(/task_id：task-new · run_id：run-new/)).toBeInTheDocument(); expect(createCalls()).toHaveLength(1); fireEvent.click(screen.getByRole('button', { name: '重试保存输入' })); await waitFor(() => expect(screen.getByText('任务工作台')).toBeInTheDocument()); expect(createCalls()).toHaveLength(1); expect(inputCalls().length).toBeGreaterThanOrEqual(2)
  })
  it('unmount during pending save produces no warning or navigation', async () => {
    let resolveSave!: (value: unknown) => void; fetchMock.mockImplementation((url) => String(url).endsWith('/inputs') ? new Promise((resolve) => { resolveSave = resolve }) : defaultFetch(url)); const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {}); const view = renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(inputCalls()).toHaveLength(1)); view.unmount(); await act(async () => resolveSave(json(SAVED))); expect(errorSpy).not.toHaveBeenCalled(); errorSpy.mockRestore()
  })
  it('unmount during pending create produces no warning, input save, or navigation', async () => {
    let resolveCreate!: (value: unknown) => void; fetchMock.mockImplementation((url) => String(url).endsWith('/tasks') ? new Promise((resolve) => { resolveCreate = resolve }) : defaultFetch(url)); const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {}); const view = renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(createCalls()).toHaveLength(1)); view.unmount(); await act(async () => resolveCreate(json(CREATED))); expect(inputCalls()).toHaveLength(0); expect(errorSpy).not.toHaveBeenCalled(); errorSpy.mockRestore()
  })
})

describe('CreateTaskPage deterministic boundaries', () => {
  it('splits Chinese and English punctuation, newlines, and hard-wraps long atoms', () => {
    expect(splitScriptIntoSegments('中文句。English sentence! next?\n最后一段；', 12)).toEqual(['中文句。', 'English sent', 'ence!next?', '最后一段；'])
    expect(splitScriptIntoSegments('abcdefghij', 3)).toEqual(['abc', 'def', 'ghi', 'j'])
  })
  it('keeps one audition player while switching voice selection', async () => {
    renderPage(); await ready(); fireEvent.click(screen.getByRole('tab', { name: '声音生成' })); await waitFor(() => expect(document.querySelector('audio')).toBeInTheDocument()); fireEvent.click(screen.getByRole('button', { name: /真实女声/ })); expect(document.querySelectorAll('audio')).toHaveLength(1)
  })
  it('recovers URL task/input state without creating another task', async () => {
    const recoveryTask = { task: { task_id: 'task-old', title: '恢复任务', summary: '恢复摘要', engine: 'whiteboard', active_run_id: 'run-old' }, active_run: { task_id: 'task-old', run_id: 'run-old' }, stages: [], warnings: [], artifacts: [], trace: { trace_id: 'trace-old', command_ids: [] } }
    const recoveryInputs = { task_id: 'task-old', saved: true, inputs: { script: '恢复文案。', style: 'style-real', voice_source: 'voice-asset', voice_asset_id: 'voice-real', visual_source: 'preset', style_asset_id: 'style-real', target_chars: 20, shots_per_image: 3, line_density: 'minimal', brand_text: '恢复品牌', include_subtitles: false, pen_text: '', stroke_detail: '' }, reference_audio: { uploaded: true, filename: 'old.wav' }, rules: { target_chars: 20, min_chars: 1, max_chars: 500 }, script_preparation: null, visual_anchor_enabled: false, execution_plan: { mode: 'legacy' } }
    fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-old/inputs')) return json(recoveryInputs); if (value.endsWith('/tasks/task-old')) return json(recoveryTask); return defaultFetch(url) })
    const view = render(<MemoryRouter initialEntries={['/tasks/new?submission_id=sub-old&task_id=task-old&run_id=run-old']} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /></Routes></MemoryRouter>); await waitFor(() => expect(screen.getByText(/已恢复 Task：task-old/)).toBeInTheDocument()); expect(screen.getByLabelText('任务名称')).toHaveValue('恢复任务'); expect(screen.getByLabelText('任务摘要')).toHaveValue('恢复摘要'); fireEvent.click(screen.getByRole('tab', { name: /视频文案/ })); await waitFor(() => expect(screen.getByLabelText('原始文案')).toHaveValue('恢复文案。')); fireEvent.click(screen.getByRole('tab', { name: /成片设置/ })); expect(screen.getByLabelText('每张图分镜数')).toHaveValue('3'); expect(screen.getByLabelText('线条绘制量')).toHaveValue('minimal'); expect(screen.getByLabelText('账号/笔身文字')).toHaveValue('恢复品牌'); expect(screen.getByRole('button', { name: '重试保存输入' })).toBeEnabled(); expect(createCalls()).toHaveLength(0); view.unmount()
  })

  it('restores the validated Task and all inputs after an actual remount', async () => {
    const recoveryTask = { task: { task_id: 'task-remount', title: '重挂载任务', summary: '重挂载摘要', engine: 'whiteboard', active_run_id: 'run-remount' }, active_run: { task_id: 'task-remount', run_id: 'run-remount' }, stages: [], warnings: [], artifacts: [], trace: null }
    const recoveryInputs = { task_id: 'task-remount', saved: true, inputs: { script: '重挂载文案。', style: 'style-real', voice_source: 'voice-asset', voice_asset_id: 'voice-real', visual_source: 'preset', style_asset_id: 'style-real', target_chars: 33, shots_per_image: 4, line_density: 'complete', brand_text: '重挂载品牌', include_subtitles: true, pen_text: '', stroke_detail: '' }, reference_audio: { uploaded: true }, rules: { target_chars: 33, min_chars: 1, max_chars: 500 }, script_preparation: null, visual_anchor_enabled: true, execution_plan: { mode: 'legacy' } }
    fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-remount/inputs')) return json(recoveryInputs); if (value.endsWith('/tasks/task-remount')) return json(recoveryTask); return defaultFetch(url) })
    const route = '/tasks/new?task_id=task-remount&run_id=run-remount'
    const renderRecovery = () => render(<MemoryRouter initialEntries={[route]} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /></Routes></MemoryRouter>)
    const first = renderRecovery(); await waitFor(() => expect(screen.getByLabelText('任务名称')).toHaveValue('重挂载任务')); first.unmount(); renderRecovery(); await waitFor(() => expect(screen.getByLabelText('任务摘要')).toHaveValue('重挂载摘要')); fireEvent.click(screen.getByRole('tab', { name: /视频文案/ })); expect(screen.getByLabelText('原始文案')).toHaveValue('重挂载文案。'); fireEvent.click(screen.getByRole('tab', { name: /成片设置/ })); expect(screen.getByLabelText('每张图分镜数')).toHaveValue('4'); expect(screen.getByLabelText('线条绘制量')).toHaveValue('complete'); expect(screen.getByRole('button', { name: '重试保存输入' })).toBeEnabled(); expect(createCalls()).toHaveLength(0)
  })

  it('navigates to the actual active workbench route after create and save', async () => {
    renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByTestId('active-workbench')).toBeInTheDocument()); expect(screen.getByTestId('active-workbench')).toHaveTextContent('任务工作台'); expect(inputCalls()).toHaveLength(1)
  })
  it('saves recovered inputs without creating a second Task', async () => {
    recoveryPage(); await waitFor(() => expect(screen.getByRole('button', { name: '重试保存输入' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: '重试保存输入' })); await waitFor(() => expect(inputSaveCalls()).toHaveLength(1)); await waitFor(() => expect(screen.getByTestId('active-workbench')).toBeInTheDocument()); expect(createCalls()).toHaveLength(0); expect(inputSaveCalls()).toHaveLength(1)
  })
  it('requires a new reference when recovery reports uploaded=false', async () => {
    const inputs = recoveryInputs(false); inputs.inputs.voice_source = 'uploaded-reference'; recoveryPage('task-recovered', 'run-recovered', inputs); await waitFor(() => expect(screen.getByRole('button', { name: '重试保存输入' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: '重试保存输入' })); fireEvent.click(screen.getByRole('tab', { name: '声音生成' })); expect(await screen.findByText('请选择参考音频')).toBeInTheDocument(); expect(inputSaveCalls()).toHaveLength(0)
  })
  it('allows omitted reference when recovery reports uploaded=true', async () => {
    const inputs = recoveryInputs(true); inputs.inputs.voice_source = 'uploaded-reference'; recoveryPage('task-recovered', 'run-recovered', inputs); await waitFor(() => expect(screen.getByRole('button', { name: '重试保存输入' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: '重试保存输入' })); await waitFor(() => expect(inputSaveCalls()).toHaveLength(1)); await waitFor(() => expect(screen.getByTestId('active-workbench')).toBeInTheDocument()); expect(inputSaveCalls()).toHaveLength(1)
  })
  it('fails closed for forged identity, Task 404, inputs 404, and recovery loading', async () => {
    fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/forged')) return json({ ...RECOVERY_TASK, task: { ...RECOVERY_TASK.task, task_id: 'server-task' } }); if (value.endsWith('/tasks/forged/inputs')) return json(recoveryInputs()); return defaultFetch(url) }); render(<MemoryRouter initialEntries={['/tasks/new?task_id=forged&run_id=run-recovered&tab=final']} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="/tasks/new" element={<CreateTaskPage />} /></Routes></MemoryRouter>); await waitFor(() => expect(screen.getByText(/身份不匹配/)).toBeInTheDocument()); expect(screen.getByRole('button', { name: '创建并保存 Task' })).toBeDisabled(); cleanup()
    fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-recovered')) return json(RECOVERY_TASK); if (value.endsWith('/tasks/task-recovered/inputs')) return json({ error: { code: 'INPUTS_NOT_FOUND', message: '输入不存在' } }, 404); return defaultFetch(url) }); renderRecoveryRoute(); await waitFor(() => expect(screen.getByText(/输入读取失败/)).toBeInTheDocument()); expect(screen.getByRole('button', { name: '创建并保存 Task' })).toBeDisabled(); cleanup()
    fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-recovered')) return json({ error: { code: 'TASK_NOT_FOUND', message: 'Task 不存在' } }, 404); if (value.endsWith('/tasks/task-recovered/inputs')) return json(recoveryInputs()); return defaultFetch(url) }); renderRecoveryRoute(); await waitFor(() => expect(screen.getByText(/Task 读取失败/)).toBeInTheDocument()); expect(screen.getByRole('button', { name: '创建并保存 Task' })).toBeDisabled(); cleanup()
    fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-recovered')) return json({ ...RECOVERY_TASK, task: { ...RECOVERY_TASK.task, active_run_id: 'other-run' } }); if (value.endsWith('/tasks/task-recovered/inputs')) return json(recoveryInputs()); return defaultFetch(url) }); renderRecoveryRoute(); await waitFor(() => expect(screen.getByText(/身份不匹配/)).toBeInTheDocument()); expect(screen.getByRole('button', { name: '创建并保存 Task' })).toBeDisabled(); cleanup()
    let resolveTask!: (value: unknown) => void; let resolveInputs!: (value: unknown) => void; fetchMock.mockImplementation((url) => { const value = String(url); if (value.endsWith('/tasks/task-recovered')) return new Promise((resolve) => { resolveTask = resolve }); if (value.endsWith('/tasks/task-recovered/inputs')) return new Promise((resolve) => { resolveInputs = resolve }); return defaultFetch(url) }); renderRecoveryRoute(); expect(screen.getByRole('button', { name: '创建并保存 Task' })).toBeDisabled(); await act(async () => { resolveTask(json(RECOVERY_TASK)); resolveInputs(json(recoveryInputs())) }); await waitFor(() => expect(screen.getByRole('button', { name: '重试保存输入' })).toBeEnabled())
  })
  it('keeps error output safe and does not leak structured details', async () => {
    fetchMock.mockImplementation((url) => String(url).endsWith('/tasks') ? json({ error: { code: 'CREATE_FAILED', message: '创建失败' }, details: '/srv/private', token: 'secret-token', request_body: '用户文案' }, 400) : defaultFetch(url)); renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByText(/创建失败/)).toBeInTheDocument()); expect(document.body).not.toHaveTextContent('/srv/private'); expect(document.body).not.toHaveTextContent('secret-token'); expect(document.body).not.toHaveTextContent('用户文案')
  })
  it('enforces title and summary required boundaries before any create request', async () => {
    renderPage(); await ready(); next(); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '这是一段满足最小长度的文案。' } }); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); expect(createCalls()).toHaveLength(0); fireEvent.click(screen.getByRole('tab', { name: '任务介绍' })); expect(screen.getByText('请输入任务名称')).toBeInTheDocument(); expect(screen.getByText('请输入任务摘要')).toBeInTheDocument()
  })
  it('accepts the documented target, shots, line, brand, and new reference boundaries', async () => {
    renderPage(); await ready(); fireEvent.change(screen.getByLabelText('任务名称'), { target: { value: '边界任务' } }); fireEvent.change(screen.getByLabelText('任务摘要'), { target: { value: '边界摘要' } }); next(); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '这是十个字的完整文案。' } }); fireEvent.change(screen.getByLabelText('目标分段长度'), { target: { value: '5' } }); fireEvent.click(screen.getByRole('tab', { name: '声音生成' })); fireEvent.click(screen.getByLabelText('上传参考音频')); fireEvent.change(screen.getByLabelText('参考音频'), { target: { files: [new File(['wav'], 'reference.wav', { type: 'audio/wav' })] } }); fireEvent.click(screen.getByRole('tab', { name: '成片设置' })); fireEvent.change(screen.getByLabelText('每张图分镜数'), { target: { value: '4' } }); fireEvent.change(screen.getByLabelText('线条绘制量'), { target: { value: 'complete' } }); fireEvent.change(screen.getByLabelText('账号/笔身文字'), { target: { value: '一二三四五六七八九十' } }); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); await waitFor(() => expect(screen.getByTestId('active-workbench')).toBeInTheDocument()); const body = inputCalls().find((call) => call[1]?.method === 'POST')![1].body as FormData; expect(body.get('target_chars')).toBe('5'); expect(body.get('shots_per_image')).toBe('4'); expect(body.get('line_density')).toBe('complete'); expect(body.get('brand_text')).toBe('一二三四五六七八九十'); expect(body.get('reference')).toBeInstanceOf(File)
  })
  it('blocks submission when the real style asset boundary is empty', async () => {
    fetchMock.mockImplementation((url) => String(url).includes('/assets/styles') ? json({ items: [], next_cursor: null, total: 0 }) : defaultFetch(url)); renderPage(); await ready(); fillIntroAndScript(); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); expect(createCalls()).toHaveLength(0); fireEvent.click(screen.getByRole('tab', { name: '视觉设置' })); expect(screen.getByText('请选择真实风格资产')).toBeInTheDocument()
  })
  it('cancels through the real queue route and blocks field boundary violations', async () => {
    renderPage(); await ready(); fireEvent.click(screen.getByRole('link', { name: '取消' })); expect(screen.getByText('任务队列')).toBeInTheDocument(); cleanup(); renderPage(); await ready(); fireEvent.change(screen.getByLabelText('任务名称'), { target: { value: '边界任务' } }); fireEvent.change(screen.getByLabelText('任务摘要'), { target: { value: '边界摘要' } }); next(); fireEvent.change(screen.getByLabelText('原始文案'), { target: { value: '短' } }); fireEvent.change(screen.getByLabelText('目标分段长度'), { target: { value: '501' } }); goFinal(); fireEvent.click(screen.getByRole('button', { name: '创建并保存 Task' })); expect(createCalls()).toHaveLength(0); fireEvent.click(screen.getByRole('tab', { name: /视频文案/ })); expect(screen.getByText(/文案至少需要/)).toBeInTheDocument(); expect(screen.getByText(/目标分段长度需在/)).toBeInTheDocument()
  })
})
