import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { BackButton } from '../components/ui/BackButton'
import { Tabs } from '../components/ui/Tabs'
import { useAsync } from '../lib/api/queries'
import { createTask, fetchCreateOptions, fetchDirectories, fetchInputs, fetchTask, MountainApiError, previewScript, uploadInputs } from '../lib/api/client'
import { fetchStyles, fetchVoices } from '../lib/api/assets'
import { getAssetBlobUrl, getVoiceContentUrl } from '../lib/api/http'
import type { DirectoryEntry, StyleTemplate, VoiceDefinition } from '../lib/api/types'

const PIPELINE_ID = 'mountain-av-v1'
const TABS = [
  { key: 'intro', label: '任务介绍' }, { key: 'script', label: '视频文案' },
  { key: 'voice', label: '声音生成' }, { key: 'output', label: '输出类型' },
  { key: 'visual', label: '视觉设置' }, { key: 'final', label: '成片设置' },
] as const
type TabKey = (typeof TABS)[number]['key']
const LINE_DENSITIES = [{ id: 'minimal', label: '精简 · 24 条' }, { id: 'standard', label: '标准 · 48 条' }, { id: 'rich', label: '丰富 · 96 条（推荐）' }, { id: 'complete', label: '完整 · 全部线条' }]
const SHOTS = [{ value: 1, label: '1 个分镜（画面最大）' }, { value: 2, label: '2 个分镜（推荐）' }, { value: 3, label: '3 个分镜' }, { value: 4, label: '4 个分镜（最省图口）' }]
const OUTPUT_COPY: Record<string, { eyebrow: string; description: string; example: string; fit: string }> = {
  whiteboard: { eyebrow: '手绘讲解', description: '线条与重点文字随旁白逐步呈现，画面节奏清晰，生成成本较低。', example: '示例：概念拆解、课程知识点、方法步骤', fit: '适合：讲解型内容与知识科普' },
  infographic: { eyebrow: '数据叙事', description: '图表、时间轴与结构化信息随旁白动态出现，突出关系和变化。', example: '示例：数据对比、趋势复盘、商业报告', fit: '适合：对比、趋势与层级类内容' },
  'infographic-remotion': { eyebrow: '数据叙事', description: '图表、时间轴与结构化信息随旁白动态出现，突出关系和变化。', example: '示例：数据对比、趋势复盘、商业报告', fit: '适合：对比、趋势与层级类内容' },
}
const VISUAL_COPY: Record<string, { description: string; detail: string }> = {
  preset: { description: '从风格库选择已验证的统一画风，无需再次上传参考素材。', detail: '适合快速制作；任务保存真实 style ID 与 revision。' },
  'custom-reference': { description: '使用风格参考图与 1–5 个人物组建立自定义视觉约束。', detail: '适合品牌化内容；当前需等待 adapter 与 capability 开放。' },
}
const PRODUCT_ENGINES = [
  { id: 'whiteboard', label: '白板动画' },
  { id: 'infographic-remotion', label: '动态信息图' },
] as const
interface FormState { title: string; summary: string; script: string; targetChars: number; voiceSource: string; voiceAssetId: string; referenceFile: File | null; engine: string; visualSource: string; styleAssetId: string; shotsPerImage: number; lineDensity: string; brandText: string; outputRoot: string; visualAnchorEnabled: boolean; includeSubtitles: boolean }
interface CreatedTask { task_id: string; run_id: string; trace_id?: string; output_root?: string; package_path?: string; package_dir?: string }

function safeError(error: unknown): string {
  if (error instanceof MountainApiError) {
    const code = error.apiError?.code
    const message = error.apiError?.message || `请求失败（${error.status}）`
    return code ? `${code}：${message}` : message
  }
  return '网络请求失败，请稍后重试'
}
function safeAsyncError(message: string | null): string {
  if (!message) return ''
  return /(?:details?|absolute|request\s*body|token|secret|bearer|password|audio|[A-Za-z]:\\|\/mnt\/|\/home\/)/iu.test(message)
    ? '网络请求失败，请稍后重试'
    : message
}
function optionLabel(option: { id: string; label: string }) { return option.label || option.id }
function formatDuration(durationMs: number): string { if (!Number.isFinite(durationMs) || durationMs <= 0) return '时长未知'; const seconds = durationMs / 1000; return seconds < 60 ? `${seconds.toFixed(1)} 秒` : `${Math.floor(seconds / 60)} 分 ${Math.round(seconds % 60)} 秒` }
function createSubmissionId(): string { if (typeof crypto === 'undefined' || typeof crypto.getRandomValues !== 'function') throw new Error('当前浏览器不支持安全随机标识生成'); const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'; const bytes = new Uint8Array(32); let token = ''; do { crypto.getRandomValues(bytes); token = Array.from(bytes, (byte) => alphabet[byte % alphabet.length]).join('') } while (new Set(token).size / token.length < 0.5); return token }
const emptyForm: FormState = { title: '', summary: '', script: '', targetChars: 45, voiceSource: 'uploaded-reference', voiceAssetId: '', referenceFile: null, engine: '', visualSource: '', styleAssetId: '', shotsPerImage: 2, lineDensity: 'rich', brandText: '', outputRoot: '', visualAnchorEnabled: true, includeSubtitles: true }

export function CreateTaskPage() {
  const navigate = useNavigate(); const location = useLocation(); const params = useMemo(() => new URLSearchParams(location.search), [location.search]); const taskId = params.get('task_id'); const runId = params.get('run_id'); const querySubmissionId = params.get('submission_id')
  const initialTab = TABS.some((tab) => tab.key === params.get('tab')) ? params.get('tab') as TabKey : 'intro'
  const hasRecoveryQuery = Boolean(taskId || runId)
  const [activeTab, setActiveTab] = useState<TabKey>(initialTab); const [form, setForm] = useState<FormState>(emptyForm); const [created, setCreated] = useState<CreatedTask | null>(null); const [submitting, setSubmitting] = useState(false); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [submitError, setSubmitError] = useState<string | null>(null); const [saveError, setSaveError] = useState<string | null>(null); const [selectedVoiceId, setSelectedVoiceId] = useState(''); const [previewEngine, setPreviewEngine] = useState<string | null>(null); const mountedRef = useRef(true); const submissionIdRef = useRef(querySubmissionId); const submittingRef = useRef(false); const defaultsAppliedRef = useRef(false); const recoveredFieldsRef = useRef(new Set<keyof FormState>()); const recoveredRef = useRef(false)
  const [directoryPickerOpen, setDirectoryPickerOpen] = useState(false); const [directoryPath, setDirectoryPath] = useState('.'); const [directoryEntries, setDirectoryEntries] = useState<DirectoryEntry[]>([]); const [directoryLoading, setDirectoryLoading] = useState(false); const [directoryError, setDirectoryError] = useState<string | null>(null); const [directorySelection, setDirectorySelection] = useState<string | null>(null)
  useEffect(() => { mountedRef.current = true; return () => { mountedRef.current = false } }, [])
  const options = useAsync(() => fetchCreateOptions(), []); const voices = useAsync(() => fetchVoices(), []); const styles = useAsync(() => fetchStyles({ kind: 'preset' }), []); const scriptPreview = useAsync(() => form.script.trim().length >= (options.data?.limits.script_min_chars ?? 10) && form.targetChars >= 5 && form.targetChars <= 500 ? previewScript({ script: form.script, target_chars: form.targetChars }) : Promise.resolve(null), [form.script, form.targetChars, options.data?.limits.script_min_chars]); const taskRecovery = useAsync(() => taskId ? fetchTask(taskId) : Promise.resolve(null), [taskId]); const inputsRecovery = useAsync(() => taskId ? fetchInputs(taskId) : Promise.resolve(null), [taskId])
  const isRecovery = hasRecoveryQuery && !created
  useEffect(() => { const value = options.data; if (!value || defaultsAppliedRef.current) return; defaultsAppliedRef.current = true; setForm((previous) => ({ ...previous, engine: recoveredFieldsRef.current.has('engine') ? previous.engine : value.defaults.engine, visualSource: recoveredFieldsRef.current.has('visualSource') ? previous.visualSource : value.defaults.visual_source, targetChars: recoveredFieldsRef.current.has('targetChars') ? previous.targetChars : value.defaults.target_chars, shotsPerImage: recoveredFieldsRef.current.has('shotsPerImage') ? previous.shotsPerImage : value.defaults.shots_per_image, lineDensity: recoveredFieldsRef.current.has('lineDensity') ? previous.lineDensity : value.defaults.line_density, visualAnchorEnabled: recoveredFieldsRef.current.has('visualAnchorEnabled') ? previous.visualAnchorEnabled : value.defaults.visual_anchor_enabled, includeSubtitles: recoveredFieldsRef.current.has('includeSubtitles') ? previous.includeSubtitles : value.defaults.include_subtitles, voiceSource: recoveredFieldsRef.current.has('voiceSource') ? previous.voiceSource : value.voice_sources.find((item) => item.available)?.id ?? previous.voiceSource })) }, [options.data])
  useEffect(() => { const first = voices.data?.items.find((item) => item.status === 'active' && item.enabled); if (first) { setSelectedVoiceId((id) => id || first.voice_id); setForm((previous) => previous.voiceAssetId ? previous : { ...previous, voiceAssetId: first.voice_id }) } }, [voices.data])
  useEffect(() => { const first = styles.data?.items.find((item) => item.status === 'active'); if (first) setForm((previous) => previous.styleAssetId ? previous : { ...previous, styleAssetId: first.style_id }) }, [styles.data])
  const taskIdentityValid = Boolean(taskId && runId && taskRecovery.data?.task?.task_id === taskId && taskRecovery.data.task.active_run_id === runId && taskRecovery.data.active_run?.task_id === taskId && taskRecovery.data.active_run?.run_id === runId)
  const recoveryLoading = isRecovery && (!taskId || !runId || taskRecovery.loading || inputsRecovery.loading)
  const recoveryError = isRecovery && (!taskId || !runId ? '恢复链接缺少 Task / Run 身份，已安全停止提交。' : taskRecovery.error ? `Task 读取失败：${safeAsyncError(taskRecovery.error)}` : inputsRecovery.error ? `输入读取失败：${safeAsyncError(inputsRecovery.error)}` : !taskRecovery.loading && taskRecovery.data && !taskIdentityValid ? 'Task 与 active Run 身份不匹配，已安全停止提交。' : !taskRecovery.loading && !taskRecovery.data ? 'Task 不存在或无法读取，已安全停止提交。' : !inputsRecovery.loading && inputsRecovery.data && !inputsRecovery.data.inputs ? 'Task 输入尚未保存，恢复流程已安全停止提交。' : null)
  const recoveryReady = !isRecovery || (!recoveryLoading && !recoveryError && taskIdentityValid && Boolean(inputsRecovery.data?.inputs))
  useEffect(() => {
    if (!taskIdentityValid || !taskRecovery.data?.task) return
    const task = taskRecovery.data.task as typeof taskRecovery.data.task & { summary?: string }
    const recovered = { title: task.title, summary: task.summary, engine: task.engine }
    ;(['title', 'summary', 'engine'] as const).forEach((key) => { if (typeof recovered[key] === 'string' && recovered[key]) recoveredFieldsRef.current.add(key) })
    setForm((previous) => ({ ...previous, title: recovered.title || previous.title, summary: recovered.summary || previous.summary, engine: recovered.engine || previous.engine }))
  }, [taskIdentityValid, taskRecovery.data])
  useEffect(() => {
    const inputs = inputsRecovery.data?.inputs
    if (!inputs || recoveredRef.current) return
    recoveredRef.current = true
    const data = inputs as Record<string, unknown>
    const values: Partial<FormState> = { script: String(data.script ?? ''), visualSource: String(data.visual_source ?? ''), styleAssetId: String(data.style_asset_id ?? data.style ?? ''), voiceSource: String(data.voice_source ?? ''), voiceAssetId: String(data.voice_asset_id ?? ''), shotsPerImage: Number(data.shots_per_image ?? 2), lineDensity: String(data.line_density ?? 'rich'), brandText: String(data.brand_text ?? data.pen_text ?? ''), includeSubtitles: Boolean(data.include_subtitles), visualAnchorEnabled: Boolean(data.visual_anchor_enabled), targetChars: Number(data.target_chars ?? inputsRecovery.data?.rules?.target_chars ?? 45) }
    Object.entries(values).forEach(([key, value]) => { if (value !== '' && value !== undefined) recoveredFieldsRef.current.add(key as keyof FormState) })
    setForm((previous) => ({ ...previous, ...Object.fromEntries(Object.entries(values).filter(([, value]) => value !== '' && value !== undefined)) as Partial<FormState> }))
  }, [inputsRecovery.data])
  useEffect(() => { if (recoveryReady && taskId && runId && taskRecovery.data?.task) setCreated({ task_id: taskId, run_id: runId, trace_id: taskRecovery.data.trace?.trace_id }) }, [recoveryReady, taskId, runId, taskRecovery.data])
  const preview = scriptPreview.data; const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((previous) => ({ ...previous, [key]: value })); const selectedVoice = voices.data?.items?.find((item) => item.voice_id === (selectedVoiceId || form.voiceAssetId)); const selectedStyle = styles.data?.items?.find((item) => item.style_id === form.styleAssetId); const option = (group: 'engines' | 'visual_sources' | 'voice_sources', id: string) => options.data?.[group].find((item) => item.id === id); const selectedEngineOption = option('engines', form.engine); const selectedVisualOption = option('visual_sources', form.visualSource); const selectedIsInfographic = form.engine === 'infographic' || form.engine === 'infographic-remotion'; const displayedEngine = previewEngine || form.engine; const isInfographic = displayedEngine === 'infographic' || displayedEngine === 'infographic-remotion'; const combinationAvailable = Boolean(selectedEngineOption?.available && selectedVisualOption?.available); const engineDisplayOptions = [...PRODUCT_ENGINES.map((product) => options.data?.engines.find((item) => item.id === product.id) ?? { ...product, available: false, reason: options.loading ? '正在读取服务端能力' : options.error ? 'create-options 读取失败' : '服务端未提供此引擎' }), ...(options.data?.engines.filter((item) => !PRODUCT_ENGINES.some((product) => product.id === item.id)) ?? [])]
  function validate() { const errors: Record<string, string> = {}; const limits = options.data?.limits; if (isRecovery && !recoveryReady) errors.recovery = '任务恢复尚未完成，当前不可提交'; if (!form.title.trim()) errors.title = '请输入任务名称'; if (!form.summary.trim()) errors.summary = '请输入任务摘要'; if (form.script.trim().length < (limits?.script_min_chars ?? 10)) errors.script = `文案至少需要 ${limits?.script_min_chars ?? 10} 个字`; if (limits && (form.targetChars < limits.target_chars_min || form.targetChars > limits.target_chars_max)) errors.targetChars = `目标分段长度需在 ${limits.target_chars_min}–${limits.target_chars_max} 之间`; if (!options.data) errors.options = 'create-options 尚未联调，当前仅可预览，暂不可提交'; const engine = option('engines', form.engine); const visual = option('visual_sources', form.visualSource); if (!engine || !engine.available) errors.engine = engine?.reason || '该输出引擎当前不可用'; if (!visual || !visual.available) errors.visualSource = visual?.reason || '该视觉来源当前不可用'; if (form.voiceSource === 'voice-asset' && !form.voiceAssetId) errors.voiceAssetId = '请选择真实音色资产'; const savedReference = inputsRecovery.data?.reference_audio?.uploaded === true; if (form.voiceSource === 'uploaded-reference' && !form.referenceFile && !savedReference) errors.referenceFile = '请选择参考音频'; if (form.visualSource === 'preset' && !form.styleAssetId) errors.styleAssetId = '请选择真实风格资产'; if (options.data && form.brandText.length > options.data.limits.brand_text_max_chars) errors.brandText = `账号文字不能超过 ${options.data.limits.brand_text_max_chars} 字`; setFieldErrors(errors); return Object.keys(errors).length === 0 }
  function buildInputs() { const data = new FormData(); data.set('script', form.script); data.set('target_chars', String(form.targetChars)); data.set('voice_source', form.voiceSource); if (form.voiceSource === 'voice-asset') data.set('voice_asset_id', form.voiceAssetId); if (form.referenceFile) data.set('reference', form.referenceFile); data.set('visual_source', form.visualSource); if (form.visualSource === 'preset') data.set('style_asset_id', form.styleAssetId); data.set('shots_per_image', String(form.shotsPerImage)); data.set('line_density', form.lineDensity); data.set('brand_text', form.brandText); data.set('visual_anchor_enabled', String(form.visualAnchorEnabled)); data.set('include_subtitles', String(form.includeSubtitles)); return data }
  async function saveInputs(id: string) { submittingRef.current = true; setSubmitting(true); setSaveError(null); try { await uploadInputs(id, buildInputs()); if (mountedRef.current) navigate(`/tasks/${encodeURIComponent(id)}`) } catch (error) { if (mountedRef.current) setSaveError(safeError(error)) } finally { submittingRef.current = false; if (mountedRef.current) setSubmitting(false) } }
  async function loadDirectory(path = '.') { setDirectoryLoading(true); setDirectoryError(null); setDirectorySelection(null); try { const response = await fetchDirectories(path); if (!mountedRef.current) return; setDirectoryPath(response.path); setDirectoryEntries(response.directories); } catch (error) { if (mountedRef.current) setDirectoryError(safeError(error)) } finally { if (mountedRef.current) setDirectoryLoading(false) } }
  function openDirectoryPicker() { setDirectoryPickerOpen(true); setDirectorySelection(null); void loadDirectory('.') }
  function closeDirectoryPicker() { setDirectoryPickerOpen(false); setDirectorySelection(null); setDirectoryError(null) }
  function chooseDirectory() { if (directorySelection !== null) update('outputRoot', directorySelection === '.' ? '' : directorySelection); closeDirectoryPicker() }
  const parentDirectory = directoryPath === '.' ? null : directoryPath.includes('/') ? directoryPath.slice(0, directoryPath.lastIndexOf('/')) || '.' : '.'
  async function submit(event: React.FormEvent) { event.preventDefault(); if (submitting || submittingRef.current || !validate()) return; if (created) { await saveInputs(created.task_id); return }; submittingRef.current = true; setSubmitting(true); setSubmitError(null); try { const submissionId = submissionIdRef.current || createSubmissionId(); submissionIdRef.current = submissionId; if (!querySubmissionId) navigate({ pathname: '/tasks/new', search: `?submission_id=${encodeURIComponent(submissionId)}` }, { replace: true }); const response = await createTask({ title: form.title.trim(), summary: form.summary.trim(), engine: form.engine, pipeline_id: PIPELINE_ID, submission_id: submissionId, ...(form.outputRoot.trim() ? { output_root: form.outputRoot.trim() } : {}) }); if (!mountedRef.current) return; const identity = { task_id: response.task_id, run_id: response.run_id, trace_id: response.trace_id, output_root: response.output_root, package_path: response.package_path, package_dir: response.package_dir }; setCreated(identity); navigate({ pathname: '/tasks/new', search: `?submission_id=${encodeURIComponent(submissionId)}&task_id=${encodeURIComponent(response.task_id)}&run_id=${encodeURIComponent(response.run_id)}` }, { replace: true }); await saveInputs(response.task_id) } catch (error) { submittingRef.current = false; if (mountedRef.current) { setSubmitError(safeError(error)); setSubmitting(false) } } }
  function next() { const index = TABS.findIndex((tab) => tab.key === activeTab); if (index < TABS.length - 1) setActiveTab(TABS[index + 1].key) }; function previous() { const index = TABS.findIndex((tab) => tab.key === activeTab); if (index > 0) setActiveTab(TABS[index - 1].key) }; const renderError = (key: string) => fieldErrors[key] && <div className="hint error" role="alert">{fieldErrors[key]}</div>; const renderAssetState = (loading: boolean, error: string | null, empty: string) => loading ? <div className="hint" role="status">正在读取真实资产…</div> : error ? <div className="error-card" role="alert">真实资产读取失败：{error}</div> : empty ? <div className="hint">{empty}</div> : null
  return <div className="page page-narrow"><BackButton to="/" label="返回任务队列" /><header className="page-head"><h1 className="page-title">新建任务</h1><p className="page-desc">按六个 Tab 完成任务输入预览；提交后创建并保存 Task，随后进入任务工作台。</p></header>{isRecovery && <div className="notice notice-info" role="status">{recoveryLoading ? '正在恢复任务输入…' : recoveryError ? recoveryError : `已恢复 Task：${taskId} · Run：${runId}`}</div>}{!hasRecoveryQuery && querySubmissionId && <div className="notice notice-info" role="status">已保留本次提交标识，刷新后可安全继续：{querySubmissionId}</div>}<Tabs items={TABS.map((tab) => tab.key === 'script' ? { ...tab, count: form.script.length } : tab)} active={activeTab} onChange={(key) => setActiveTab(key as TabKey)} />{options.error && <div className="notice notice-warn" role="status">create-options 读取失败：{safeAsyncError(options.error)}。当前仅可预览，暂不可提交。</div>}<form onSubmit={submit} noValidate><div id={`tab-panel-${activeTab}`} role="tabpanel" aria-labelledby={`tab-${activeTab}`}>
    {activeTab === 'intro' && <div className="tab-pane card"><div className="field"><label htmlFor="title">任务名称</label><input id="title" className="input" value={form.title} onChange={(event) => update('title', event.target.value)} disabled={submitting} />{renderError('title')}</div><div className="field"><label htmlFor="summary">任务摘要</label><textarea id="summary" className="textarea" rows={5} value={form.summary} onChange={(event) => update('summary', event.target.value)} disabled={submitting} />{renderError('summary')}</div></div>}
    {activeTab === 'script' && <div className="tab-pane card"><div className="copy-split"><div className="copy-col"><label className="copy-label" htmlFor="script">原始文案</label><textarea id="script" className="textarea" rows={9} value={form.script} onChange={(event) => update('script', event.target.value)} disabled={submitting} placeholder="粘贴要制作成视频的文案…" />{renderError('script')}<div className="copy-count">字数统计：<b>{form.script.length}</b> 字</div></div><div className="copy-col"><div className="copy-label-row"><span className="copy-label">权威分段结果</span><span className="copy-tag">{preview?.algorithm_version || '读取中'}</span></div>{scriptPreview.loading ? <div className="hint" role="status">正在读取服务端权威分段结果…</div> : scriptPreview.error ? <div className="error-card" role="alert">权威分段读取失败：{safeAsyncError(scriptPreview.error)}</div> : preview ? <><ol className="script-preview-units" aria-label="权威分段结果">{preview.voice_units.map((unit) => <li key={unit.unit_id} data-boundary-reason={unit.boundary_reason} data-undersize-reason={unit.undersize_reason || undefined}><span className="script-preview-unit-text">{unit.text}</span><span className="hint">#{unit.order} · 段落 {unit.paragraph_index} · {unit.boundary_reason}{unit.undersize_reason ? ` · ${unit.undersize_reason}` : ''} · raw {unit.source_range.start}–{unit.source_range.end} · normalized {unit.normalized_range.start}–{unit.normalized_range.end}</span></li>)}</ol><div className="copy-count">权威规则：目标 <b>{preview.rules.target_chars}</b> · 最小 <b>{preview.rules.min_chars}</b> · 最大 <b>{preview.rules.max_chars}</b> · <b>{preview.voice_units.length}</b> 段</div></> : <div className="hint">输入足够文案后读取服务端权威分段结果。</div>}<p className="hint">原始文案按原样提交并保留审计语义；显示单元严格使用服务端返回的 newline-free text，布局空白见 source mapping。</p></div></div><div className="field"><label htmlFor="targetChars">目标分段长度</label><input id="targetChars" className="input input-sm" type="number" min={1} max={500} value={form.targetChars} onChange={(event) => update('targetChars', Number(event.target.value))} disabled={submitting} />{options.data && <span className="hint">服务端范围：{options.data.limits.target_chars_min}–{options.data.limits.target_chars_max}</span>}{renderError('targetChars')}</div></div>}
    {activeTab === 'voice' && <div className="tab-pane card">
      <h3 className="card-title">声音生成</h3>
      <p className="zone-desc">音色选择与「音色管理」使用同一真实数据源。选中项会作为整支成片的配音母版；样例音频用于试听，不会替代任务输入。</p>
      <div className="field"><span className="copy-label">音色来源</span><div className="choice-row">{options.data?.voice_sources.map((source) => <label key={source.id} className={'source-choice' + (!source.available ? ' unsupported' : '')}><input aria-label={optionLabel(source)} type="radio" name="voiceSource" checked={form.voiceSource === source.id} onChange={() => source.available && update('voiceSource', source.id)} disabled={!source.available || submitting} /><span><strong>{optionLabel(source)}</strong><small>{source.id === 'voice-asset' ? '复用音色库中已验证的声音' : '上传一段参考音频进行声音克隆'}{!source.available && ` · 不可用：${source.reason || '服务端能力未就绪'}`}</small></span></label>)}</div></div>
      <h4 className="section-title">音色库示例</h4>
      <p className="zone-desc">选择任一可用音色后，可在右侧试听并核对语言、情绪模式和引擎限制。</p>
      {renderAssetState(voices.loading, voices.error, (voices.data?.items ?? []).length === 0 ? '真实音色列表为空。' : '')}
      {(voices.data?.items ?? []).length > 0 && <div className="voice-layout"><div className="opt-grid voice-list">{(voices.data?.items ?? []).map((voice: VoiceDefinition) => <button type="button" key={voice.voice_id} className={'opt-card' + (form.voiceAssetId === voice.voice_id ? ' selected' : '') + (voice.status !== 'active' || !voice.enabled ? ' unsupported' : '')} onClick={() => { if (voice.status === 'active' && voice.enabled) { update('voiceAssetId', voice.voice_id); setSelectedVoiceId(voice.voice_id) } }} disabled={voice.status !== 'active' || !voice.enabled || submitting}><span className="opt-name">{voice.name}{voice.status !== 'active' || !voice.enabled ? '（不可用）' : ''}</span><span className="opt-desc">{voice.description || voice.tags.join(' · ') || '真实音色资产'}</span><span className="asset-facts">{voice.language || '语言未标注'} · {voice.emotion_mode || '默认情绪'} · {formatDuration(voice.duration_ms)}</span></button>)}</div><div className="voice-audition"><span className="copy-label">选中音色与试听</span>{selectedVoice ? <><div className="selected-asset-head"><strong>{selectedVoice.name}</strong><span className={'status-pill ' + (selectedVoice.availability_status || (selectedVoice.enabled ? 'available' : 'limited'))}>{selectedVoice.availability_status === 'verified' ? '已验证' : selectedVoice.availability_status === 'limited' ? '受限' : '可用'}</span></div><div className="asset-facts">{selectedVoice.language || '语言未标注'} · {selectedVoice.emotion_mode || '默认情绪'} · {formatDuration(selectedVoice.duration_ms)}{selectedVoice.engine ? ` · ${selectedVoice.engine}` : ''}</div>{selectedVoice.example_text && <p className="sample-copy">“{selectedVoice.example_text}”</p>}<audio aria-label={`${selectedVoice.name}试听`} controls preload="none" src={getVoiceContentUrl(selectedVoice.voice_id)} />{selectedVoice.status_note && <span className="hint">{selectedVoice.status_note}</span>}{selectedVoice.compatibility?.limitations?.length ? <span className="hint">限制：{selectedVoice.compatibility.limitations.join('；')}</span> : null}</> : <span className="hint">请选择可用音色</span>}</div></div>}
      {renderError('voiceAssetId')}
      <div className="field reference-upload"><label htmlFor="referenceFile">参考音频</label><p className="zone-desc">使用“上传参考音频”时请选择清晰、无背景音乐的人声。上传成功与创建 Task 是独立动作；保存失败不会要求重选已由后端保留的素材。</p><input id="referenceFile" type="file" accept="audio/*,.wav,.mp3,.m4a,.ogg,.flac" onChange={(event) => update('referenceFile', event.target.files?.[0] ?? null)} disabled={submitting} />{form.referenceFile && <div className="hint">已选择：{form.referenceFile.name}</div>}{created && !form.referenceFile && inputsRecovery.data?.reference_audio?.uploaded && <div className="hint">参考音频已保存；浏览器刷新后需重新选择文件才能再次上传。</div>}{renderError('referenceFile')}</div>
    </div>}
    {activeTab === 'output' && <div className="tab-pane card">
      <h3 className="card-title">选择成片形态</h3><p className="zone-desc">输出引擎决定画面如何运动；它与视觉来源是两个独立选择。不可用状态完全来自服务端 create-options。</p>
      <div className="opt-grid output-grid">{engineDisplayOptions.map((item) => { const copy = OUTPUT_COPY[item.id] || { eyebrow: '输出引擎', description: '由服务端提供的成片渲染方式。', example: '示例以实际引擎能力为准', fit: '适用范围请查看服务端说明' }; return <div className="output-option-shell" key={item.id}><button type="button" className={'opt-card output-card' + (form.engine === item.id ? ' selected' : '') + (!item.available ? ' unsupported' : '')} onClick={() => { if (item.available) { update('engine', item.id); setPreviewEngine(null) } }} disabled={!item.available || submitting}><span className="option-eyebrow">{copy.eyebrow}</span><span className="opt-name">{optionLabel(item)}{!item.available && <span className="status-pill limited">暂未开放</span>}</span><span className="opt-desc">{copy.description}</span><span className="option-example">{copy.example}</span><span className="option-fit">{copy.fit}</span>{!item.available && <span className="option-reason">服务端：{item.reason || '能力未就绪'}</span>}</button>{!item.available && item.id === 'infographic-remotion' && <button type="button" className="btn btn-ghost btn-sm output-preview-button" aria-label="查看未开放引擎的成片说明" onClick={() => { setPreviewEngine(item.id); setActiveTab('final') }} disabled={submitting}>预览成片设置</button>}</div> })}</div>
      {!options.data && <div className="hint">等待 create-options 返回可用引擎；固定产品项暂时保持禁用。</div>}{renderError('engine')}
      <div className="difference-note"><strong>关键差异</strong><span>白板动画强调“逐笔讲解”，动态信息图强调“结构与数据变化”；两者共享文案、声音和字幕输入，但成片设置不同。</span></div>
    </div>}
    {activeTab === 'visual' && <div className="tab-pane card">
      <h3 className="card-title">视觉来源</h3><p className="zone-desc">选择预设风格，或提供自定义风格参考与人物组。真实资产来自 Style API；当前组合是否可用由服务端决定。</p>
      <div className="opt-grid">{options.data?.visual_sources.map((item) => { const copy = VISUAL_COPY[item.id] || { description: '服务端提供的视觉来源。', detail: '具体素材和约束以资产 API 为准。' }; return <button type="button" key={item.id} className={'opt-card' + (form.visualSource === item.id ? ' selected' : '') + (!item.available ? ' unsupported' : '')} onClick={() => item.available && update('visualSource', item.id)} disabled={!item.available || submitting}><span className="opt-name">{optionLabel(item)}{!item.available && <span className="status-pill limited">暂未开放</span>}</span><span className="opt-desc">{copy.description}</span><span className="option-example">{copy.detail}</span>{!item.available && <span className="option-reason">服务端：{item.reason || '能力未就绪'}</span>}</button> })}</div>
      {options.data && <div className={'notice ' + (combinationAvailable ? 'notice-ok' : 'notice-warn')} role="status" aria-label="当前视觉组合状态"><strong>当前组合：</strong>{selectedEngineOption?.label || form.engine || '未选择引擎'} + {selectedVisualOption?.label || form.visualSource || '未选择视觉来源'}。{combinationAvailable ? `服务端已开放，可使用 ${PIPELINE_ID} 保存任务。` : `暂不可提交：${selectedEngineOption?.reason || selectedVisualOption?.reason || '服务端能力未就绪'}`}</div>}
      {form.visualSource === 'preset' && <div className="field"><span className="copy-label">预设风格库示例</span><p className="zone-desc">以下条目来自真实 Style API。点击卡片选择；预览图作为独立参考素材展示，不会被浏览器缓存数据替代。</p>{renderAssetState(styles.loading, styles.error, styles.data?.items.length === 0 ? '真实风格列表为空。' : '')}<div className="style-grid">{styles.data?.items.map((style: StyleTemplate) => <button type="button" key={style.style_id} className={'style-card' + (form.styleAssetId === style.style_id ? ' selected' : '') + (style.status !== 'active' ? ' unsupported' : '')} onClick={() => style.status === 'active' && update('styleAssetId', style.style_id)} disabled={style.status !== 'active' || submitting}>{style.preview_asset_id ? <img src={getAssetBlobUrl(style.preview_asset_id)} alt={`${style.name} 预览`} /> : <span className="style-thumb placeholder">无预览</span>}<span className="opt-name">{style.name}{style.status !== 'active' ? '（不可用）' : ''}</span><span className="opt-desc">{style.description || style.tags.join(' · ') || '真实风格资产'}</span></button>)}</div>{selectedStyle && <div className="selected-style-preview">{selectedStyle.preview_asset_id ? <img src={getAssetBlobUrl(selectedStyle.preview_asset_id)} alt={`${selectedStyle.name} 独立参考预览`} /> : <span className="style-thumb placeholder">无预览</span>}<div><span className="copy-label">当前选中风格</span><strong>{selectedStyle.name}</strong><span className="asset-facts">revision {selectedStyle.revision} · {selectedStyle.engine || '通用引擎'} · {selectedStyle.tags.join(' · ') || '无标签'}</span><p>{selectedStyle.description || '暂无风格说明'}</p></div></div>}{renderError('styleAssetId')}</div>}
      {form.visualSource === 'custom-reference' && <div className="notice notice-info"><strong>自定义参考需要：</strong>一组风格参考图与 1–5 个人物。服务端开放后才会读取真实 custom Style 列表并允许提交；当前不会使用原型 mock 或 localStorage 代替。</div>}
      {renderError('visualSource')}
    </div>}
    {activeTab === 'final' && <div className="tab-pane card">
      <h3 className="card-title">成片设置 · {isInfographic ? '动态信息图' : '白板动画'}</h3><p className="zone-desc">本页只展示所选引擎适用的成片控件；也可以从输出类型页只读预览尚未开放的引擎说明。</p>
      {previewEngine && <div className="notice notice-warn" role="status" aria-label="只读引擎预览"><strong>只读预览：</strong>动态信息图未被当前服务端开放，本页不会把它写入任务。真实提交引擎仍为 {selectedEngineOption?.label || form.engine || '未选择'}。</div>}
      {!isInfographic && <>
        <div className="vs-row"><div className="mini-field"><label htmlFor="shotsPerImage">每张图分镜数</label><select id="shotsPerImage" className="select" value={form.shotsPerImage} onChange={(event) => update('shotsPerImage', Number(event.target.value))} disabled={submitting}>{SHOTS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><span className="hint">Shot 是同一张图片的渲染分镜，不会额外生成图片。</span></div><div className="mini-field"><label htmlFor="lineDensity">线条绘制量</label><select id="lineDensity" className="select" value={form.lineDensity} onChange={(event) => update('lineDensity', event.target.value)} disabled={submitting}>{LINE_DENSITIES.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><span className="hint">控制白板线稿的绘制丰富度。</span></div><div className="mini-field"><label htmlFor="brandText">账号/笔身文字</label><input id="brandText" className="input" maxLength={options.data?.limits.brand_text_max_chars} value={form.brandText} onChange={(event) => update('brandText', event.target.value)} disabled={submitting} placeholder="例如：你的账号名" /><span className="hint">显示在白板笔身或品牌位置。</span>{renderError('brandText')}</div></div>
        <label className="feature-switch"><input type="checkbox" checked={form.visualAnchorEnabled} onChange={(event) => update('visualAnchorEnabled', event.target.checked)} disabled={submitting} /><span><strong>画面锚定重点文字</strong><small>每个分镜显示一条与旁白对应的重点锚定文字。</small></span></label>
        <label className="feature-switch"><input type="checkbox" checked={form.includeSubtitles} onChange={(event) => update('includeSubtitles', event.target.checked)} disabled={submitting} /><span><strong>生成字幕</strong><small>成片会预装与 Voice Unit 同步的中文字幕。</small></span></label>
      </>}
      {isInfographic && <div className="infographic-features"><div className="fs-feature"><span className="fs-feature-tag">语义时间轴</span><span className="fs-feature-desc">每个元素绑定真实旁白，讲到对应内容时才出现。</span></div><div className="fs-feature"><span className="fs-feature-tag">智能结构</span><span className="fs-feature-desc">自动选择对比、时间轴、层级、因果、案例或总结结构。</span></div><div className="fs-feature"><span className="fs-feature-tag">文字安全</span><span className="fs-feature-desc">标题与论点由程序排版，不让图片模型生成不可控中文。</span></div><label className="feature-switch"><input type="checkbox" checked={form.includeSubtitles} onChange={(event) => update('includeSubtitles', event.target.checked)} disabled={submitting} /><span><strong>生成字幕</strong><small>成片会预装与 Voice Unit 同步的中文字幕。</small></span></label></div>}
      <div className="field"><label htmlFor="outputRoot">输出目录</label><div className="output-root-row"><input id="outputRoot" className="input" value={form.outputRoot} onChange={(event) => update('outputRoot', event.target.value)} disabled={submitting} placeholder="留空使用项目 outputs/" /><button type="button" className="btn btn-ghost" onClick={openDirectoryPicker} disabled={submitting}>选择目录</button></div><span className="hint">留空时由后端使用项目默认 outputs/；目录会由后端规范化并校验。</span></div>
      <div className="execution-card"><label htmlFor="executionStrategy">执行策略</label><select id="executionStrategy" className="select" value="auto" disabled><option value="auto">自动完成（当前支持）</option><option value="manual" disabled>手动完成（服务端尚未开放）</option></select><p>创建后各阶段自动连续推进；阶段视图用于理解、恢复和返工。当前上传输入契约未开放人工 Stage 门禁，因此不会伪装为可提交选项。</p><fieldset className="manual-preview" disabled><legend>手动完成能力预览（未开放）</legend><label><input type="radio" name="manualModePreview" />每道工序都等待人工触发</label><label><input type="radio" name="manualModePreview" />仅在选中的 Stage 前等待</label><div className="stage-chip-row" aria-label="可选择的人工触发阶段"><span>画面锚定</span><span>配音</span><span>分镜</span><span>插画</span><span>动画/渲染</span><span>合成</span></div><small>未选中的 Stage 将连续执行，直到下一个人工门禁。</small></fieldset><p className="hint">若未来视觉来源由人工 Codex 提供插画，插画阶段将等待外部成果，不会显示为无人值守自动完成。</p></div>
      {!previewEngine && !combinationAvailable && <div className="notice notice-warn" role="status">当前引擎/视觉来源组合未开放，以下设置仅供预览，无法创建任务：{selectedEngineOption?.reason || selectedVisualOption?.reason || '服务端能力未就绪'}</div>}
      <div className="summary-card" aria-label="最终汇总"><h3>最终汇总</h3><p>任务：{form.title || '未填写'}</p><p>文案：{form.script.length} 字，权威预览 {preview?.voice_units.length ?? 0} 段</p><p>真实提交引擎：{selectedEngineOption?.label || '待服务端选项'}</p><p>视觉：{selectedStyle?.name || form.visualSource || '待选择'}</p><p>音色：{selectedVoice?.name || (form.voiceSource === 'uploaded-reference' ? '参考音频' : '待选择')}</p><p>输出目录：{form.outputRoot.trim() || '后端默认项目 outputs/'}</p><p>{selectedIsInfographic ? '信息图：语义时间轴 · 智能结构 · 文字安全' : `白板：每图 ${form.shotsPerImage} 个分镜 · 线条 ${form.lineDensity} · 锚定 ${form.visualAnchorEnabled ? '是' : '否'}`} · 字幕 {form.includeSubtitles ? '是' : '否'}</p><p>执行：自动完成</p>{created && <>{(created.output_root || created.package_path || created.package_dir) && <p>后端输出：{created.package_path || created.package_dir || created.output_root}</p>}<p>Task ID：{created.task_id}</p></>}</div>
    </div>}
    </div>{submitError && <div className="error-card" role="alert">创建 Task 失败：{submitError}</div>}{saveError && <div className="error-card" role="alert"><strong>Task 已创建，输入保存失败</strong><span className="sug">{saveError}</span><span className="sug">task_id：{created?.task_id} · run_id：{created?.run_id}</span>{created && (created.package_path || created.package_dir || created.output_root) && <span className="sug">后端输出：{created.package_path || created.package_dir || created.output_root}</span>}<button type="button" className="btn btn-ghost" onClick={() => created && navigate(`/tasks/${encodeURIComponent(created.task_id)}`)}>进入任务工作台</button></div>}
    {directoryPickerOpen && <div className="modal-mask" role="dialog" aria-modal="true" aria-label="输出目录选择器" onClick={closeDirectoryPicker}><div className="modal-card directory-picker" onClick={(event) => event.stopPropagation()}><h2 className="modal-title">选择输出目录</h2><div className="directory-picker-path"><span className="copy-label">项目目录</span><code>{directoryPath}</code></div>{directoryError && <div className="error-card" role="alert">目录读取失败：{directoryError}</div>}{directoryLoading ? <div className="hint" role="status">正在读取目录…</div> : <div className="directory-list" role="list">{directoryEntries.map((entry) => <button type="button" className="btn btn-ghost directory-entry" key={entry.path} onClick={() => void loadDirectory(entry.path)}>{entry.name}<span>进入</span></button>)}{directoryEntries.length === 0 && <div className="hint">当前目录没有直属子目录。</div>}</div>}<div className="modal-foot"><button type="button" className="btn btn-ghost btn-sm" onClick={() => parentDirectory && void loadDirectory(parentDirectory)} disabled={!parentDirectory || directoryLoading}>返回上级</button><button type="button" className="btn btn-primary btn-sm" onClick={() => setDirectorySelection(directoryPath)}>选择当前目录</button><button type="button" className="btn btn-ghost btn-sm" onClick={closeDirectoryPicker}>取消</button><button type="button" className="btn btn-primary btn-sm" onClick={chooseDirectory} disabled={directorySelection === null}>确认</button></div></div></div>}<div className="actions"><button type="button" className="btn btn-ghost" onClick={previous} disabled={activeTab === 'intro' || submitting}>上一步</button>{activeTab !== 'final' ? <button type="button" className="btn btn-primary" onClick={next} disabled={submitting}>下一步</button> : <button type="submit" className="btn btn-primary" disabled={submitting || !options.data || (isRecovery && !recoveryReady)}>{created ? '重试保存输入' : '创建并保存 Task'}</button>}<Link to="/" className="btn btn-ghost">取消</Link></div>
    </form></div>
}
